# Generated by Django 5.1 on 2024-08-20 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gis_app.wells'),
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
