# Generated by Django 5.1 on 2024-08-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0003_rename_location_files_well'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='internalStorageParth',
            field=models.FilePathField(default='no_path/no'),
            preserve_default=False,
        ),
    ]
