# Generated by Django 5.1 on 2024-08-21 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0005_rename_internalstorageparth_files_internalstoragepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
