# Generated by Django 5.1 on 2024-08-21 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gis_app', '0006_alter_files_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='internalHash',
            field=models.CharField(default='NO HASH', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
